### ISSUE TITLE
Security Breach

### ISSUE THREAD

**Issue by BRAVO68WEB** [issadarkthing/discordjs-pagination#1]
### Exposer
- https://www.npmjs.com/package/@jiman24/discordjs-pagination?activeTab=code
- ![image](https://github.com/issadarkthing/discordjs-pagination/assets/41448663/36e6c211-068a-4d23-8507-50fc47c44d8f)

### Breach App
- Token on the first line is live bot token
- Discord Bot :- (Test) Spawn Art of War#1937

## Severity :- Medium

P.S.:- It was hard to find you and let you know about this ...

**Comment by raziman18** [comment]
I already made an update to this package that exclude the `.env` file. Thank you for your notice anyways.
